train:
  batch_size: 64
  epochs: 500
  log_interval: 2
  lr: 2e-4

logger:
  results_path: "results/"
  checkpoint_path: "checkpoints/"
  enable_wandb: False

system:
  device: "cuda:0"
  seed: 42

model:
  output_features_filters: 3
  augment_output_features: False
  output_features_dim: 60  # Aligned with input_features_dim
  verbose: False
  num_hiddens: 200
  num_residual_layers: 2
  num_residual_hiddens: 4
  use_kaiming_normal: False
  input_features_type: 'mfcc'
  input_features_dim: 60  # Aligned with the number of data points in each channel
  input_features_filters: 3  # Aligned with the number of channels
  augment_input_features: False
  embedding_dim: 64
  num_embeddings: 128
  commitment_cost: 0.25
  decay: 0.0
  use_jitter: False
  jitter_probability: 0.12
  record_codebook_stats: False

run_date: ${now:%Y_%m_%d_%H_%M}
